
;<PROB.1 FIVE NUMBERS ARE STORED IN CONSECUTIVE MEMORY LOCATIONS STARTING
;FROM 9000H. SORT THE NUMBER IN ASCENDING/DESCENDING ORDER.>
jmp start
;data
;code
start: nop
MVI B,05H         ;OUTER LOOP COUNTER
OUTLOOP: LXI H,9000H      ;OUTER LOOP
MVI C,04H
INLOOP: nop       ;INNER LOOP
MOV A,M           ;STORING VALUE OF CONSECUITIVE ELEMENTS IN A AND D
INX H
MOV D,M
DCX H
CMP D
CC SWAP           ;IF SMALLER CALL THE SWAP SUBROUTINE
INX H
DCR C
JNZ INLOOP       
DCR B
JNZ OUTLOOP
hlt
SWAP: nop      ;SWAPPING WITH THE NEXT ADDRESS 
MOV M,D
INX H
MOV M,A
DCX H
RET